/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./views/AboutUs.vue')['default']
    AppFooter: typeof import('./layout/components/AppFooter.vue')['default']
    AppHeader: typeof import('./layout/components/AppHeader.vue')['default']
    BannerView: typeof import('./components/home/BannerView.vue')['default']
    CButton: typeof import('./components/common/CButton.vue')['default']
    PartnerView: typeof import('./components/partner/PartnerView.vue')['default']
    ProductView: typeof import('./components/home/ProductView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesView: typeof import('./components/home/ServicesView.vue')['default']
    SvgIcon: typeof import('./components/common/SvgIcon.vue')['default']
  }
}
